spring:
  thymeleaf:
    mode: HTML

  profiles:
    active: dev

  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 20MB

qiniu_url: ${myenv:http://qhx6myqd8.hn-bkt.clouddn.com/}